variables: variables-sync.yml

templates:

  global:
    no_entries_ok: yes

  anchors:
    _sftp_list: &sftp_list
      host: '{? sftp.host ?}'
      username: '{? sftp.username ?}'
      private_key: '{? sftp.privatekey ?}'
      private_key_pass: '{? sftp.private_key_pass ?}'

  notify-sync:
    notify:
      entries:
        title: "FlexGet - {? local.hostname ?}"
        message: "Downloaded {{title}}"
        via:
          - pushbullet:
              api_key: '{? pushbullet.apikey ?}'

tasks:

  sync-series:
    sftp_list:
      <<: *sftp_list
      dirs:
        - '{? remote.downloads ?}/series/'
    accept_all: yes
    sftp_download:
      to: '{? local.downloads ?}/series/'
    template: notify-sync
  
  sync-movies:
    sftp_list:
      <<: *sftp_list
      dirs:
        - '{? remote.downloads ?}/movies/'
    accept_all: yes
    sftp_download:
      to: '{? local.downloads ?}/movies/'
    template: notify-sync

  sort-anime:
    filesystem: '{? local.downloads ?}/series/'
    configure_series:
      from:
        filesystem: '{? local.videos ?}/Anime/'
    move:
      to: "{? local.videos ?}/Anime/{{series_name}}/"

  sort-tv:
    filesystem: '{? local.downloads ?}/series/'
    configure_series:
      from:
        filesystem: '{? local.videos ?}/TV/'
    move:
      to: "{? local.videos ?}/TV/{{series_name}}/Season {{series_season}}/"

  sort-movies:
    filesystem: '{? local.downloads ?}/movies/'
    accept_all: yes
    move:
      to: "{? local.videos ?}/Movies/"

schedule:
  - tasks: [sync-series, sync-movies]
    schedule:
      minute: "*/30"
      hour: 8-23
  - tasks: [sort-anime, sort-tv, sort-movies]
    schedule:
      minute: 10,40
      hour: 8-23
