variables: variables.yml

web_server:
  web_ui: yes

templates:

  global:
    no_entries_ok: yes

  anchors:

    _filesystem: &filesystem
      retrieve: files
      regexp: '.*\.(mp4|mkv)$'

    _ntfysh: &ntfysh
      topic: '{? ntfysh.topic ?}'
      url: '{? ntfysh.url ?}'
      username: '{? ntfysh.username ?}'
      password: '{? ntfysh.password ?}'

    _trakt_list: &trakt_list
      username: '{? trakt.username ?}'
      account: '{? trakt.username ?}'
      strip_dates: yes
  
  notify-download:
    notify:
      entries:
        title: "Downloading"
        message: >
          {% if series_name is defined %}{{series_name}} {{series_id|pad(2)}}
          {% elif tmdb_name is defined %}{{tmdb_name}} [{{tmdb_year}}]
          {% else %}{{title|replace('.mkv','')|replace('.mp4','')}}
          {% endif %}
        via:
          - ntfysh:
              <<: *ntfysh

  notify-sort:
    notify:
      entries:
        title: "Downloaded"
        message: >
          {% if task|re_search("anime") %}{{title|replace('.mkv','')}}
          {% elif task|re_search("tv") %}{{series_name}} {{series_id|pad(2)}}
          {% elif task|re_search("movie") %}{{tmdb_name}} [{{tmdb_year}}]
          {% else %}{{title|replace('.mkv','')|replace('.mp4','')}}
          {% endif %}
        via:
          - ntfysh:
              <<: *ntfysh

tasks:

  download-anime:
    rss:
      url: '{? feeds.anime ?}'
      all_entries: no
    include: anime.yml
    transmission:
      host: '{? transmission.host ?}'
      content_filename: "{{series_name}} {{series_id|pad(2)}}"
      path: '{? transmission.downloads ?}/anime/'
    template: notify-download

  download-tv:
    rss:
      url: '{? feeds.tv ?}'
      all_entries: no
      silent: yes
      escape: yes
    include: tv.yml
    transmission:
      host: '{? transmission.host ?}'
      path: '{? transmission.downloads ?}/.tv/'
    template: notify-series
  
  download-movies:
    rss:
      url: '{? feeds.movies ?}'
      all_entries: no
    regexp:
      reject_excluding:
        - '{? regexp.filter ?}'
      from: title
    tmdb_lookup: yes
    list_match:
      from:
        - movie_list: movies
    transmission:
      host: '{? transmission.host ?}'
      path: '{? transmission.downloads ?}/movies/'
    template: notify-download

  update-movie-list:
    limit:
      amount: 10
      from:
        trakt_list:
          <<: *trakt_list
          list: '{? trakt.movies ?}'
          type: movies
    accept_all: yes
    tmdb_lookup: yes
    list_add:
      - movie_list: movies
    list_remove:
      - trakt_list:
          <<: *trakt_list
          list: '{? trakt.movies ?}'
          type: movies

  sort-anime:
    filesystem:
      <<: *filesystem
      path: '{? local.downloads ?}/anime/'
    accept_all: yes
    disable: builtins
    move:
      to: "{? local.videos ?}/Anime/{{title|re_replace(' \\d{2,3}$','')}}/"
    template: notify-sort
  
  sort-tv:
    filesystem:
      <<: *filesystem
      recursive: yes
      path: '{? local.downloads ?}/tv/'
    metainfo_series: yes
    accept_all: yes
    disable: builtins
    move:
      to: "{? local.videos ?}/TV/{{series_name}}/Season {{series_season}}/"
      rename: "{{series_name|replace(':',' -')}} {{series_id|pad(2)}}"
      clean_source: 100
    template: notify-sort

  move-movies:
    filesystem: 
      <<: *filesystem
      recursive: yes
      path: '{? local.downloads ?}/.movies/'
    accept_all: yes
    tmdb_lookup: yes
    disable: builtins
    move:
      to: "{? local.videos ?}/Movies/{{tmdb_name}} ({{tmdb_year}})"
      rename: "{{tmdb_name|replace(':',' -')}} ({{tmdb_year}})"
      clean_source: 100
    template: notify-sort

  cleanup-transmission:
    from_transmission:
      host: '{? transmission.host ?}'
      only_complete: yes
    disable: builtins
    accept_all: yes
    transmission:
      host: '{? transmission.host ?}'
      action: remove
  
schedules:
  - tasks: [ download-anime, download-tv, sort-*, cleanup-transmission ]
    schedule:
      minute: "*/15"
  - tasks: [ update-movie-list, download-movies, move-movies ]
    schedule:
      minute: 10,25,40,55
