variables: variables.yml

templates:

  anchors:
    _deluge: &deluge
      path: '/home/{? local.username ?}/.incomplete'
      ratio: 1.0

    _entries: &entries
      title: 'FlexGet - {? local.hostname ?}'
      via:
        - pushbullet '{? pushbullet.apikey ?}'
    
  deluge-series:
    deluge:
      <<: *deluge
      content_filename: "{{series_name|replace(':',' -')}} {{series_id|pad(2)}}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"
      movedone: '/home/{? local.username ?}/downloads/flexget/series/'
  
  deluge-movies:
    deluge:
      <<: *deluge
      content_filename: "{{tmdb_name|replace(':',' -')}} [{{tmdb_year}}]"
      movedone: '/home/{? local.username ?}/downloads/flexget/movies/'

  notify-series:
    notify:
      entries:
        <<: *entries
        message: "Downloading {{series_name|replace(':',' -')}} {{series_id|pad(2)}}"

  notify-movies:
    notify:
      entries:
        <<: *entries
        message: "Downloading {{tmdb_name|replace(':',' -')}} [{{tmdb_year}}]"

tasks:

  anime:
    rss: '{? feeds.anime ?}'
    configure_series:
      from:
        my_anime_list:
          username: '{? myanimelist.username ?}'
    template:
      - deluge-series
      - notify-series

  tv:
    rss: '{? feeds.tv ?}'
    configure_series:
      from:
        thetvdb_list:
          username: '{? tvdb.username ?}'
          account_id: '{? tvdb.account ?}'
          strip_dates: yes
    template:
      - deluge-series
      - notify-series
  
  movies:
    rss: '{? feeds.movies ?}'
    crossmatch:
      from:
        - letterboxd:
            username: '{? letterboxd.username ?}'
            list: '{? letterboxd.list ?}'
            sort_by: release_ascending
      fields:
        - title
      action: accept
      exact: no
    tmdb_lookup: yes
    template:
      - deluge-movies
      - notify-movies

schedules:
  - tasks: [anime, tv]
    interval:
      minutes: 30
  - tasks: movies
    schedule:
      hour: 2
